### ISSUE TITLE
JDBC Stored procedure tests fail with SQL Server

### ISSUE THREAD

**Issue by quotidian-ennui** [adaptris/interlok#866]
# Expectation

If you switch to MSSQL as opposed to MySQL to run the stored procedure tests, then the tests should pass in the same way, they don't against the standard microsoft sql server image. Most of the tests do work, enough don't for it to be investigated.

Note that I tried this with _9.2.1.jre8_ (current develop branch) and _9.4.1.jre11_ (jre11 since we're java 11 for interlok 4.x)

# Steps to recreate

### MSSQL in docker

The docker compose file is this (very simple).

```yaml
version: '3.2'
services:
  mssql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: mssql_server
    container_name: mssql_server
    environment:
      - SA_PASSWORD=Yukon900
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
```
### properties configuration 

I used `src/test/resources/default-test.properties.template.[machine-name]` to override the defaults.

```properties
default.jdbc.storedproc.tests.enabled=true
default.jdbc.storedproc.url=jdbc:sqlserver://localhost:1433;databaseName=
default.jdbc.storedproc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
default.jdbc.storedproc.database=InterlokTest
default.jdbc.storedproc.username=sa
default.jdbc.storedproc.password=Yukon900
default.jdbc.storedproc.teststatement=
# Currently supported vendors for testing; "mysql" / "sqlserver".
default.jdbc.storedproc.vendor=sqlserver
default.jdbc.storedproc.url.params=
```

### Test Output

```console
Running: Test class com.adaptris.core.jdbc.StoredProcedureProducerTest

com.adaptris.core.jdbc.StoredProcedureProducerTest > testMultiResultSetXmlTranslator FAILED
    java.lang.AssertionError at StoredProcedureProducerTest.java:1013

com.adaptris.core.jdbc.StoredProcedureProducerTest > testMultipleResultSetsFirstRowMetadataTranslator FAILED
    java.lang.AssertionError at StoredProcedureProducerTest.java:954

com.adaptris.core.jdbc.StoredProcedureProducerTest > testMultipleResultSetsMetadataTranslator FAILED
    java.lang.AssertionError at StoredProcedureProducerTest.java:910
Running: Test class com.adaptris.jdbc.JdbcStoredProcedureTest

com.adaptris.jdbc.JdbcStoredProcedureTest > testManyResultsets FAILED
    java.lang.AssertionError at JdbcStoredProcedureTest.java:381

com.adaptris.jdbc.JdbcStoredProcedureTest > testStoredProcedureMultiParamConstructor FAILED
    java.lang.AssertionError at JdbcStoredProcedureTest.java:397
```
